baseURL = "https://utilitarianism.net/"
googleAnalytics = "G-91NYS1B7E1"
title = "Utilitarianism"
languageCode = "en-us"
theme = ["ananke"]
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[languages]
  [languages.en]
    title = "Utilitarianism.net"
    weight = 1
  # [languages.jp]
  #   title = "i18n test"
  #   weight = 2
[Params]
  images = ["img/social.png"]
  pdf = false # boolean to toggle when generating PDF
  search = false # boolean to toggle when generating the search index
  production = false # boolean to toggle if this is a production build