defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[languages]
  [languages.en]
    disabled = false
    languageCode = "en-US"
    title = "Utilitarianism.net"
    baseURL = "https://utilitarianism.net/"
    weight = 1
    [languages.en.services]
      [languages.en.services.googleAnalytics]
        ID = 'G-91NYS1B7E1'
  [languages.es]
    disabled = true
    languageCode = "es-ES"
    title = "Utilitarismo.net"
    baseURL = "https://utilitarianismo.net/"
    weight = 2
    [languages.es.services]
      [languages.es.services.googleAnalytics]
        ID = 'G-ADD-ID'
  [languages.de]
    disabled = true
    languageCode = "de-DE"
    title = "Utilitarismus.net"
    baseURL = "https://utilitarianismus.net/"
    weight = 3
    [languages.de.services]
      [languages.de.services.googleAnalytics]
        ID = 'G-ADD-ID'
[Params]
  images = ["img/social.png"]
  # WARNING - below 3 (pdf, search, production) should all be "false"
  #           they are automatically toggled when using the build steps
  #           needless to say, do not rename these variables ;)
  pdf = false # boolean to toggle when generating PDF
  search = false # boolean to toggle when generating the search index
  production = false # boolean to toggle if this is a production build
