baseURL = 'https://utilitarianism.net/'
googleAnalytics = 'G-91NYS1B7E1'
title = 'Utilitarianism'
languageCode = 'en-us'
theme = ["ananke"]
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[languages]
  [languages.en]
    title = 'Utilitarianism.net'
    weight = 1
  # [languages.jp]
  #   title = 'i18n test'
  #   weight = 2
